modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="welcomejump"
version="1.0.0"
displayName="Welcome Jump"
authors="notkpc"
description='''Todos los jugadores saltan cuando alguien entra al servidor.'''

# Dependencia de Forge
[[dependencies.welcomejump]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

# Dependencia de Minecraft
[[dependencies.welcomejump]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"